# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AxxessAssessment' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'

  use_frameworks!
  # Pods for AxxessAssessment

  target 'AxxessAssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AxxessAssessmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
