# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AxxessAssessment' do
  use_frameworks!

  pod 'SnapKit'
  pod 'Alamofire', '~> 4.5'


  target 'AxxessAssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AxxessAssessmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
